version: "3.9"

services:
  pipeline:
    build: .
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./source:/app/source:ro
      - ./dbt:/app/dbt
      - ./pipeline:/app/pipeline
    command: python --version
